# Generated by Django 3.2.9 on 2021-11-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='autor_name',
            new_name='author_name',
        ),
    ]
