# Generated by Django 3.2.9 on 2021-11-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_autor_name_author_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.Author'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_category',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.GameCategory'),
        ),
    ]
