# Generated by Django 3.2.9 on 2021-11-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='games',
        ),
    ]
