# Generated by Django 3.2.9 on 2021-11-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_order_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='games',
            field=models.ManyToManyField(related_name='orders', through='games.OrderItem', to='games.Game'),
        ),
    ]
